### ISSUE TITLE
Need example

### ISSUE THREAD

**Issue by painhardcore** [PGower/django-ldap3-sync#1]
Trying to configure this app with AD,but can do right config :(

Need an example for simple situation.

**Comment by painhardcore** [comment]
i made this in the settings:

LDAP_CONFIG = {"servers":[{"address":"xx.xx.xx.xx"}],
               "bind_user":"testuser@example.com","bind_password":"password"}
LDAP_SYNC_BASE = 'OU="Users",OU="Staff",DC="example",DC="com"'
LDAP_SYNC_USER_ATTRIBUTES = {
    "sAMAccountName": "username"
}
LDAP_SYNC_GROUP_ATTRIBUTES = {
    "cn": "name",
}

and got
ERROR:ldap3_sync.management.commands.syncldap:LDAP Object CN=Somename Somesecondname,OU=Users,OU=Staff,DC= example,DC=com is missing a field: sAMAccountName

what should i do to fix it?

**Comment by adamturski** [comment]
This errors happened because user_ldap_attribute_names proeprty is dict_keys object - should be list object.

django-ldap3-sync 0.1.11
syncldap.py (line: 301)
self.user_ldap_attribute_names = self.user_attribute_map.keys()

This helped me:
self.user_ldap_attribute_names = list(self.user_attribute_map.keys())

**Comment by PGower** [comment]
Im not sure I understand this issue. On my system the result of dict.keys() is a `<type 'list'>`.

If you are getting the error:

`ERROR:ldap3_sync.management.commands.syncldap:LDAP Object CN=Somename Somesecondname,OU=Users,OU=Staff,DC= example,DC=com is missing a field: sAMAccountName`

It means that the LDAP objects that are being returned dont have a sAMAccountName attribute.
Are you using Active Directory or some other LDAP system? Is your filter strcutured to only return user objects? (Or at least only objects that have a sAMAccountName field)

**Comment by adamturski** [comment]
## In python3 method keys return object dict_keys.

Python 3.4.3 (v3.4.3:9b73f1c3e601, Feb 24 2015, 22:43:06) [MSC v.1600 32 bit (In
tel)] on win32
Type "help", "copyright", "credits" or "license" for more information.

> > > d=dict()
> > > d.keys()
> > > 
> > > ## dict_keys([])

Error:
ERROR:ldap3_sync.management.commands.syncldap:LDAP Object CN=Somename Somesecondname,OU=Users,OU=Staff,DC= example,DC=com is missing a field: sAMAccountName

This error is related with dict_keys object returned from keys method. Of course this error may occurs when something went wrong with AD configuration or bad filter etc. but in my case this helped me.

**Comment by adamturski** [comment]
I found.

user_ldap_attribute_names is pass as parameter to a method:
SmartLdapSearcher.search
and then is pass to a method:
ldap3.core.Connection.search
and then to a method:
ldap3.operation.search.py -> search_operation()
and in line 366 we have:

if not isinstance(attributes, SEQUENCE_TYPES):
        attributes = [NO_ATTRIBUTES]

This causes that parameter attributes is cleared because is not one of SEQUENCE_TYPES(list, tuple, GeneratorType). Parameter attributes is dict_keys!
